//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Authorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public int trainee_id { get; set; }
        public string trainee_name { get; set; }
        public byte[] trainee_img { get; set; }
        public Nullable<int> training_id { get; set; }
    
        public virtual training training { get; set; }
    }
}
